
notify = ["/Users/jgoon/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-5.6-sol"
model_reasoning_effort = "low"
approval_policy = "on-request"
approvals_reviewer = "user"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[marketplaces.openai-bundled]
last_updated = "2026-07-23T00:40:38Z"
source_type = "local"
source = "/Users/jgoon/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-08-02T20:07:33Z"
source_type = "local"
source = "/Users/jgoon/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/jgoon/.codex"
CODEX_HOME = "/Users/jgoon/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,d0b55a8f9e8e7e9c88421416ea4ce9542c302abf43aa7fc871be4553ea70dd26"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.715.72359"
SKY_CUA_SERVICE_PATH = "/Users/jgoon/.codex/plugins/cache/openai-bundled/computer-use/1.0.1000451/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
keepRemoteControlAwakeWhilePluggedIn = true
git-pull-request-merge-method = "squash"
git-show-sidebar-pr-icons = true
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"

[projects."/Users/jgoon/github/openpoker"]
trust_level = "trusted"

[projects."/Users/jgoon/Documents/Codex/2026-05-27/can-you-make-my-tmux-theme"]
trust_level = "trusted"

[projects."/Users/jgoon/Documents/Codex/2026-05-27/can-you-find-ibrahim-shah-on"]
trust_level = "trusted"

[projects."/Users/jgoon/Documents/Codex/2026-05-27/help-me-install-mattpocock-skills"]
trust_level = "trusted"

[projects."/Users/jgoon/Documents/Codex/2026-05-27/can-you-check-if-yadm-has"]
trust_level = "trusted"

[projects."/Users/jgoon"]
trust_level = "trusted"

[projects."/Users/jgoon/github/hub"]
trust_level = "trusted"

[projects."/Users/jgoon/github/terraform"]
trust_level = "trusted"

[projects."/Users/jgoon/github"]
trust_level = "trusted"

[projects."/Users/jgoon/github/create-t3-app"]
trust_level = "trusted"

[projects."/Users/jgoon/Documents/Codex/2026-06-20/create-a-folder-in-github-and"]
trust_level = "trusted"

[projects."/Users/jgoon/Documents/Codex/2026-06-20/can-you-install-or-check-if"]
trust_level = "trusted"

[projects."/Users/jgoon/github/snapp"]
trust_level = "trusted"

[projects."/Users/jgoon/.treehouse"]
trust_level = "trusted"

[projects."/Users/jgoon/github/herdr"]
trust_level = "trusted"

[projects."/Users/jgoon/github/rizzbot"]
trust_level = "trusted"

[projects."/Users/jgoon/vault"]
trust_level = "trusted"

[projects."/Users/jgoon/github/t3code"]
trust_level = "trusted"

[projects."/Users/jgoon/github/pimsg"]
trust_level = "trusted"

[projects."/Users/jgoon/github/hermes-agent"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "current-dir"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[shell_environment_policy.set]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,d0b55a8f9e8e7e9c88421416ea4ce9542c302abf43aa7fc871be4553ea70dd26"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/jgoon/.codex"

[hooks.state]

[hooks.state."/Users/jgoon/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:121a0cdd8d2446ec990ad14f950c511877125852d21f8f91d664d65ee5c7cbb2"
enabled = true

[hooks.state."/Users/jgoon/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:6d7b99c8d40e51358218bc180b717ab30ba3522efe4a0a9dced2ade50fbff780"
enabled = true
