# dev tools

brew 'yadm'
brew 'neovim'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'zoxide'


# apps

cask 'visual-studio-code'
cask 'alfred'
cask 'karabiner-elements'
cask 'obsidian'

