# dev tools

brew 'yadm'
brew 'neovim'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'zoxide'
brew 'nvm'
brew 'yarn'
brew 'pure' # zsh prompt


# apps

cask 'visual-studio-code'
cask 'alfred'
cask 'karabiner-elements'
cask 'obsidian'
cask 'aldente'
cask 'shottr'
cask 'mactex'
