# HM module: tailnet SSH aliases for every fleet machine.
#
# Hybrid contract with Coder (and anything else that rewrites ~/.ssh/config):
#
#   1. HM OWNS ~/.ssh/hosts-generated.conf outright — a store symlink to a
#      generated file with one Host block per fleet peer. Coder never
#      touches this file.
#
#   2. HM owns EXACTLY ONE LINE of ~/.ssh/config: the Include at the very
#      top. Everything below stays hand-maintained / coder-managed. HM
#      writes it once via home.activation, and HEALS it on every rebuild:
#      if coder regenerates ~/.ssh/config and drops or moves the Include,
#      the next rebuild re-prepends it.
#
#   Why the Include must be line 1: Host/Match blocks extend to EOF
#   (comments do not end them). A trailing Include — e.g. after coder's
#   `Match host *.coder` or a last `Host github.com` block — falls inside
#   the last block's scope and never matches. Verified the hard way
#   (vault: "tailnet ssh aliases").
#
#   3. SSH keys are NOT managed here. authorized_keys distribution stays
#      imperative (keys are per-machine secrets; a future port could move
#      pubkeys into fleet.nix once all boxes are on the flake).
#
# `selfAttr` — this machine's fleet attr — comes from specialArgs
# (extraSpecialArgs in the flake's mkDarwin/mkHome). Hosts don't need to
# set anything; the flake sets it per-attr.
#
# Migration: ts-ssh-sync (~/.local/bin) bootstraps boxes not yet on the
# flake. Once a host switches to the flake, this module's symlink replaces
# the script's generated file; remove the script then.
{
  config,
  lib,
  user,
  selfAttr ? null,
  ...
}:
let
  fleet = import ../../fleet.nix;
  sshDir = "${config.home.homeDirectory}/.ssh";
  genFile = "${sshDir}/hosts-generated.conf";
  includeLine = "Include ${genFile}";

  block =
    name: ip:
    ''
      Host ${name}
        HostName ${ip}
        User ${user}
        IdentityFile ~/.ssh/id_ed25519
        IdentitiesOnly yes
        AddKeysToAgent yes
    '';

  # every peer except self, one Host block each
  blocks = lib.concatStringsSep "\n\n" (
    lib.mapAttrsToList block (lib.filterAttrs (n: _: n != selfAttr) fleet)
  );

  genContent = ''
    # Generated by the nix flake (modules/home/ssh-aliases.nix) — DO NOT EDIT.
    # Fleet: work, mini, pc, personal. Rerun nothing; a rebuild refreshes.
    # Managed include: see the Include line at the top of ~/.ssh/config.
  '' + "\n" + blocks + "\n";
in
{
  config = {
    home.file.".ssh/hosts-generated.conf".text = genContent;

    home.activation.ensureSshInclude = lib.hm.dag.entryAnywhere ''
      # heal the Include at line 1 of ~/.ssh/config (coder may have
      # rewritten the file and dropped it)
      if [ -f "${sshDir}/config" ]; then
        if ! head -n 3 "${sshDir}/config" | grep -qxF "${includeLine}"; then
          printf '%s\n' "${includeLine}" > "${sshDir}/config.new"
          cat "${sshDir}/config" >> "${sshDir}/config.new"
          mv "${sshDir}/config.new" "${sshDir}/config"
          chmod 600 "${sshDir}/config"
        fi
      else
        printf '%s\n' "${includeLine}" > "${sshDir}/config"
        chmod 600 "${sshDir}/config"
      fi
      # drop the legacy script's include comment block, if present
      sed -i.bak-ts '/^# --- TAILNET ALIASES (ts-ssh-sync) ---$/,+2d' "${sshDir}/config" 2>/dev/null || true
      rm -f "${sshDir}/config.bak-ts" 2>/dev/null || true
    '';
  };
}
