# fleet: ssh aliases for every tail net peer. fleet.nix is the map;
# this module generates ~/.ssh/hosts-generated.conf (one Host block per
# peer, self excluded via selfAttr) and keeps the Include at line 1 of
# ~/.ssh/config — coder rewrites that file's other sections, and a
# trailing Include is swallowed by an unterminated Match/Host block, so
# line 1 is load-bearing (vault: "tailnet ssh aliases"). Keys stay
# imperative — per-machine secrets.
{
  config,
  lib,
  user,
  selfAttr ? null,
  ...
}:
let
  fleet = import ../../fleet.nix;
  sshDir = "${config.home.homeDirectory}/.ssh";
  genFile = "${sshDir}/hosts-generated.conf";
  includeLine = "Include ${genFile}";

  block =
    name: ip:
    ''
      Host ${name}
        HostName ${ip}
        User jgoon
        IdentityFile ~/.ssh/id_ed25519
        IdentitiesOnly yes
        AddKeysToAgent yes
    '';

  # every peer except self, one Host block each. peers take the fleet
  # user (jgoon) — NOT the local user: devspace runs as `coder`, but every
  # peer box wants jgoon. User jgoon on work/mini/pc is a no-op (same user).
  peers = lib.filterAttrs (n: _: n != selfAttr) fleet;
  blocks = lib.concatStringsSep "\n\n" (lib.mapAttrsToList block peers);
  fleetList = lib.concatStringsSep ", " (lib.attrNames fleet);

  genContent = ''
    # Generated by the nix flake (modules/home/ssh-aliases.nix) — DO NOT EDIT.
    # Fleet: ${fleetList}.
  '' + "\n" + blocks + "\n";
in
{
  config = {
    home.file.".ssh/hosts-generated.conf".text = genContent;

    home.activation.ensureSshInclude = lib.hm.dag.entryAnywhere ''
      if [ -f "${sshDir}/config" ]; then
        if ! head -n 3 "${sshDir}/config" | grep -qxF "${includeLine}"; then
          printf '%s\n' "${includeLine}" > "${sshDir}/config.new"
          cat "${sshDir}/config" >> "${sshDir}/config.new"
          mv "${sshDir}/config.new" "${sshDir}/config"
          chmod 600 "${sshDir}/config"
        fi
      else
        printf '%s\n' "${includeLine}" > "${sshDir}/config"
        chmod 600 "${sshDir}/config"
      fi
    '';
  };
}
