# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e3b3da45-3b52-4fa2-94a3-bf82ff4358f8";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-e3b3da45-3b52-4fa2-94a3-bf82ff4358f8".device = "/dev/disk/by-uuid/e3b3da45-3b52-4fa2-94a3-bf82ff4358f8";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-e3b3da45-3b52-4fa2-94a3-bf82ff4358f8";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-e3b3da45-3b52-4fa2-94a3-bf82ff4358f8";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/755E-242B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-5fa656db-87e7-4454-9cc7-9d8ce7014ce8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
