#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# tailnet-join facts
LOGIN_SERVER="https://headscale.jgoon.com"
HS_INSTANCE="i-04013ad3adc217213"
HS_REGION="us-west-1"
HS_USER_ID="1"

TJ_TARGET="${1:-}"
TJ_HOST="${2:-}"

banner "Join a machine to the tailnet"

# ── Stage 1 · Preflight — resolve target, find CLI, check state ──────────
stage "Preflight — target"

if [[ -z "$TJ_TARGET" ]]; then
  while true; do
    printf '  %sJoin which?%s [here | mac | pc] ' "$BOLD" "$RESET"
    read -r TJ_TARGET || true
    case "$TJ_TARGET" in
      here|pc|mac) break ;;
      *) warn "answer: here (this mac), mac (another mac over ssh), or pc (NixOS box)" ;;
    esac
  done
fi
if [[ "$TJ_TARGET" == "mac" && -z "$TJ_HOST" ]]; then
  printf '  %sssh alias of the mac?%s ' "$BOLD" "$RESET"
  read -r TJ_HOST || true
fi

TS=""
state=""
case "$TJ_TARGET" in
  here)
    for p in /usr/local/bin/tailscale /opt/homebrew/bin/tailscale "/Applications/Tailscale.app/Contents/MacOS/Tailscale"; do
      [[ -x "$p" ]] && TS="$p" && break
    done
    if [[ -z "$TS" ]]; then
      warn "no tailscale CLI found on this mac"
      note "bootstrap first: nix + yadm clone, then 'make here' (installs the cask)"
      exit 1
    fi
    note "CLI: $TS"
    state=$("$TS" status --json 2>/dev/null | grep -o '"BackendState": *"[A-Za-z]*"' | cut -d'"' -f4)
    ;;
  mac)
    [[ -n "$TJ_HOST" ]] || { warn "mac target needs an ssh alias"; exit 1; }
    out=$(ssh -o BatchMode=yes -o ConnectTimeout=10 "$TJ_HOST" 'sh -s' <<'RS' || true
TS=""
for p in /usr/local/bin/tailscale /opt/homebrew/bin/tailscale "/Applications/Tailscale.app/Contents/MacOS/Tailscale"; do
  [ -x "$p" ] && TS="$p" && break
done
if [ -n "$TS" ]; then
  "$TS" status --json 2>/dev/null | grep -o '"BackendState": *"[A-Za-z]*"' | cut -d'"' -f4
else
  echo NOCLI
fi
RS
)
    if [[ "$out" == "NOCLI" ]]; then
      warn "$TJ_HOST: no tailscale CLI found"
      note "bootstrap that mac first (nix + yadm clone + 'make there'), then re-run"
      exit 1
    fi
    if [[ -z "$out" ]]; then
      warn "ssh to $TJ_HOST failed — is it awake / on the tailnet?"
      exit 1
    fi
    state="$out"
    ;;
  pc)
    out=$(ssh -o BatchMode=yes -o ConnectTimeout=10 pc 'sh -s' <<'RS' || true
tailscale status --json 2>/dev/null | grep -o '"BackendState": *"[A-Za-z]*"' | cut -d'"' -f4
RS
)
    if [[ -z "$out" ]]; then
      warn "ssh to pc failed — is it awake / on the tailnet?"
      exit 1
    fi
    state="$out"
    ;;
  *)
    warn "unknown target '$TJ_TARGET' — use: here | mac <host> | pc"
    exit 1
    ;;
esac

if [[ "$state" == "Running" ]]; then
  printf '  %s✓ already on the tailnet — nothing to do%s\n' "$GREEN" "$RESET"
  exit 0
fi
note "current state: ${state:-unknown} — joining it now"

# ── Stage 2 · AWS SSO — credentials for the mint ────────────────────────
stage "AWS SSO — credentials"
say "Minting the join key runs headscale commands on the EC2 box via SSM."
if [[ -z "$HS_INSTANCE" ]]; then
  warn "no control-plane instance ID — expected it in $_secrets"
  note "echo 'i-…' > ""$_secrets""   (chmod 600; gitignored — `make hs-nodes` reads the same file)"
  note "or export HS_INSTANCE=… and re-run"
  exit 1
fi
if aws sts get-caller-identity --profile dev-admin >/dev/null 2>&1; then
  note "token fresh — skipping sign-in"
else
  step "your browser will open to the AWS access portal — sign in, then Allow"
  if ! aws sso login --profile dev-admin; then
    warn "login didn't complete in this shell"
    pause "Finish it in the browser, then press Enter to re-check"
  fi
  if ! aws sts get-caller-identity --profile dev-admin >/dev/null 2>&1; then
    warn "still no credentials — run: aws sso login --profile dev-admin"
    exit 1
  fi
  note "signed in ✓"
fi

# ── Stage 3 · Mint — fresh pre-auth key ──────────────────────────────────
stage "Mint — pre-auth key (reusable, 30d)"
confirm "Mint a fresh key on the headscale server?" || { warn "aborted — nothing was changed"; exit 0; }
note "sending SSM command (takes a few seconds)…"
CID=$(aws ssm send-command --profile dev-admin --region "$HS_REGION" \
  --instance-ids "$HS_INSTANCE" \
  --document-name "AWS-RunShellScript" \
  --comment "tailnet-join: mint key" \
  --parameters "commands=[\"docker exec headscale headscale preauthkeys create -u $HS_USER_ID --reusable --expiration 30d\"]" \
  --output text --query "Command.CommandId") || { warn "SSM send failed"; exit 1; }

KEY=""
i=0
while [[ "$i" -lt 12 ]]; do
  sleep 3
  # stdout ends with a trailing blank line — match the key itself, not tail
  KEY=$(aws ssm get-command-invocation --profile dev-admin --region "$HS_REGION" \
    --command-id "$CID" --instance-id "$HS_INSTANCE" \
    --query StandardOutputContent --output text 2>/dev/null \
    | grep -m1 -E '^(hskey|tskey)' || true)
  [[ -n "$KEY" ]] && break
  i=$((i+1))
done
case "$KEY" in
  hskey*|tskey*) : ;;
  *) warn "no key from SSM (got: '${KEY:-}')"
     note "inspect: aws ssm get-command-invocation --command-id $CID --instance-id $HS_INSTANCE"
     exit 1 ;;
esac
note "minted ${KEY:0:12}… (reusable, expires in 30d; full value never shown — it's consumed at the next stage)"

# ── Stage 4 · Join — tailscale up on the target ──────────────────────────
stage "Join — ${TJ_TARGET}${TJ_HOST:+ $TJ_HOST}"
JOINED_HOST=""
case "$TJ_TARGET" in
  here)
    # no sudo on macs: the CLI talks to the root daemon's socket; the daemon joins
    if "$TS" up --login-server "$LOGIN_SERVER" --auth-key "$KEY" \
        --accept-dns=false >/dev/null 2>&1; then
      JOINED_HOST=$("$TS" status --json --peers=false 2>/dev/null \
        | grep -o '"HostName": *"[^"]*"' | head -1 | cut -d'"' -f4 || true)
      printf '  %s✓ joined%s as %s\n' "$GREEN" "$RESET" "${JOINED_HOST:-this mac}"
    else
      warn "tailscale up failed"
      note "retry by hand: $TS up --login-server $LOGIN_SERVER --accept-dns=false"
      exit 1
    fi
    ;;
  mac)
    printf '%s\n' "$KEY" | ssh -o BatchMode=yes "$TJ_HOST" \
      'cat > /tmp/tj-key && chmod 600 /tmp/tj-key' || { warn "key delivery to $TJ_HOST failed"; exit 1; }
    out=$(ssh -o BatchMode=yes "$TJ_HOST" 'sh -s' <<'RS' || true
TS=""
for p in /usr/local/bin/tailscale /opt/homebrew/bin/tailscale "/Applications/Tailscale.app/Contents/MacOS/Tailscale"; do
  [ -x "$p" ] && TS="$p" && break
done
if "$TS" up --login-server https://headscale.jgoon.com \
    --auth-key "$(cat /tmp/tj-key)" --accept-dns=false >/dev/null 2>&1; then
  echo "JOINED-OK $("$TS" status --json --peers=false 2>/dev/null | grep -o '"HostName": *"[^"]*"' | head -1 | cut -d'"' -f4)"
else
  echo JOINED-FAIL
fi
rm -f /tmp/tj-key
RS
)
    case "$out" in
      JOINED-OK*)
        JOINED_HOST="${out#JOINED-OK }"
        printf '  %s✓ joined%s as %s\n' "$GREEN" "$RESET" "${JOINED_HOST:-$TJ_HOST}"
        ;;
      *) warn "join failed on $TJ_HOST — ssh in and retry by hand (the CLI there knows the flags)"
         exit 1 ;;
    esac
    ;;
  pc)
    printf '%s\n' "$KEY" | ssh -o BatchMode=yes pc \
      'cat > /tmp/tj-key && chmod 600 /tmp/tj-key' || { warn "key delivery to pc failed"; exit 1; }
    if confirm "join pc now over ssh? (you'll type the sudo password)"; then
      if ssh -t -o BatchMode=yes pc \
        'sudo tailscale up --login-server https://headscale.jgoon.com --auth-key "$(cat /tmp/tj-key)" --accept-dns=false'; then
        printf '  %s✓ joined%s as pc\n' "$GREEN" "$RESET"
        ssh -o BatchMode=yes pc 'rm -f /tmp/tj-key' || true
        JOINED_HOST="pc"
      else
        warn "join failed — the key is still staged at pc:/tmp/tj-key (600)"
        note "ssh pc, then: sudo tailscale up --login-server https://headscale.jgoon.com --auth-key \"\$(cat /tmp/tj-key)\" --accept-dns=false"
        exit 1
      fi
    else
      note "key staged at pc:/tmp/tj-key (600). Join it yourself:"
      say "  ssh pc"
      say "  sudo tailscale up --login-server https://headscale.jgoon.com --auth-key \"\$(cat /tmp/tj-key)\" --accept-dns=false"
      say "  rm /tmp/tj-key"
      pause "once it's joined, press Enter to verify"
      JOINED_HOST="pc"
    fi
    ;;
esac

# ── Stage 5 · Verify — node registered on the control plane ─────────────
stage "Verify — registration on headscale"
note "listing nodes via SSM (a few seconds)…"
CID=$(aws ssm send-command --profile dev-admin --region "$HS_REGION" \
  --instance-ids "$HS_INSTANCE" \
  --document-name "AWS-RunShellScript" \
  --comment "tailnet-join: list nodes" \
  --parameters 'commands=["docker exec headscale headscale nodes list"]' \
  --output text --query "Command.CommandId") || { warn "SSM send failed"; exit 1; }
sleep 4
OUT=$(aws ssm get-command-invocation --profile dev-admin --region "$HS_REGION" \
  --command-id "$CID" --instance-id "$HS_INSTANCE" \
  --query StandardOutputContent --output text || true)

say "control plane nodes:"
printf '%s\n' "$OUT"

label="${JOINED_HOST:-$TJ_TARGET}"
if [[ -n "$label" ]] && grep -qi "$label" <<<"$OUT"; then
  printf '  %s✓ '%s' found in the node list%s\n' "$GREEN" "$label" "$RESET"
else
  warn "'$label' not found in the list above"
  note "if the join printed a machine registration key instead, approve it:"
  note "  docker exec headscale headscale nodes register --key <KEY> --user jgoon   (on $HS_INSTANCE)"
fi
pause "Press Enter to finish"

finish
